OnlineShop.Web/Models/ErrorViewModel.cs
namespace OnlineShop.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

OnlineShop.Web/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using OnlineShop.Web.Models;

namespace OnlineShop.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

OnlineShop.Web/ViewComponents/Handlers/MainSite/MainSite_BannerViewComponent.cs
using Microsoft.AspNetCore.Cors.Infrastructure;
using Microsoft.AspNetCore.Mvc;

namespace OnlineShop.Web.ViewComponents.Handlers.MainSite;

public class MainSite_BannerViewComponent : ViewComponent
{
    public IViewComponentResult Invoke()
    {
        
        return View("/ViewComponents/Views/MainSite/MainSite_BannerView.cshtml");
    }
}

OnlineShop.Web/ViewComponents/Handlers/MainSite/MainSite_ProductViewComponent.cs
using Microsoft.AspNetCore.Cors.Infrastructure;
using Microsoft.AspNetCore.Mvc;

namespace OnlineShop.Web.ViewComponents.Handlers.MainSite;

public class MainSite_ProductViewComponent : ViewComponent
{
    public IViewComponentResult Invoke()
    {
        return View("/ViewComponents/Views/MainSite/MainSite_ProductView.cshtml");
    }
}

OnlineShop.Web/ViewComponents/Handlers/MainSite/MainSite_SectionTitleViewComponent.cs
using Microsoft.AspNetCore.Cors.Infrastructure;
using Microsoft.AspNetCore.Mvc;

namespace OnlineShop.Web.ViewComponents.Handlers.MainSite;

public class MainSite_SectionTitleViewComponent : ViewComponent
{
    public record SectionTitleViewModel(string Title, string Description);

    public IViewComponentResult Invoke(string title, string description)
    {
        
        return View("/ViewComponents/Views/MainSite/MainSite_SectionTitleView.cshtml", new SectionTitleViewModel(title, description));
    }
}

OnlineShop.Web/ViewComponents/Handlers/MainSite/MainSite_SidebarMenuViewComponent.cs
using Microsoft.AspNetCore.Cors.Infrastructure;
using Microsoft.AspNetCore.Mvc;

namespace OnlineShop.Web.ViewComponents.Handlers.MainSite;

public class MainSite_SidebarMenuViewComponent : ViewComponent
{
    public IViewComponentResult Invoke()
    {
        
        return View("/ViewComponents/Views/MainSite/MainSite_SidebarMenuView.cshtml");
    }
}

OnlineShop.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<section class="product-section pt-0">
    <div class="container-fluid p-0">
        <div class="custom-row">

            @await Component.InvokeAsync("MainSite_SidebarMenu")

            <div class="content-col">
                @await Component.InvokeAsync("MainSite_Banner")

                @await Component.InvokeAsync("MainSite_SectionTitle", new { title = "محصولات پرفروش", description = "یک دستیار مجازی محصولات را از لیست شما جمع آوری می کند" })

                @await Component.InvokeAsync("MainSite_Product")

                @await Component.InvokeAsync("MainSite_SectionTitle", new { title = "تازه ترین محصولات", description = "یک دستیار مجازی محصولات را از لیست شما جمع آوری می کند" })
               
                @await Component.InvokeAsync("MainSite_Product")

            </div>
        </div>
    </div>
</section>
<!-- Product Section End -->

OnlineShop.Web/Views/Shared/Partials/_Footer.cshtml
<!-- Footer Section Start -->
<footer class="footer-sm">
    <div class="container-fluid-xs">
        <div class="sub-footer">
            <div class="reserve">
                <h6 class="text-content">راست چین و فارسی سازی شده توسط : <b>فارس کد</b></h6>
            </div>

            <div class="payment">
                <img src="/siteAssets/images/payment/1.png" class="blur-up lazyload" alt="">
            </div>
        </div>
    </div>
</footer>
<!-- Footer Section End -->
<!-- Tap to top start -->
<div class="back-to-top">
    <a id="back-to-top" href="#">
        <i class="fas fa-chevron-up"></i>
    </a>
</div>
<!-- Tap to top end -->

OnlineShop.Web/Views/Shared/Partials/_Header.cshtml
<!-- Loader Start -->
<div class="fullpage-loader">
    <span></span>
    <span></span>
    <span></span>
    <span></span>
    <span></span>
    <span></span>
</div>
<!-- Loader End -->
<!-- Header Start -->
<header class="pb-0 fixed-header">
    <div class="top-nav top-header">
        <div class="container-fluid-xs">
            <div class="row">
                <div class="col-12">
                    <div class="navbar-top">
                        <button class="navbar-toggler d-xl-none d-inline navbar-menu-button" type="button"
                                data-bs-toggle="offcanvas" data-bs-target="#primaryMenu">
                            <span class="navbar-toggler-icon navbar-toggler-icon-2">
                                <i class="fa-solid fa-bars"></i>
                            </span>
                        </button>

                        <div class="middle-box">
                            <div class="location-box">
                                <button class="btn location-button" data-bs-toggle="modal"
                                        data-bs-target="#locationModal">
                                    <span class="location-arrow">
                                        <i data-feather="map-pin"></i>
                                    </span>
                                    <span class="locat-name">مکان شما</span>
                                    <i class="fa-solid fa-angle-down"></i>
                                </button>
                            </div>

                            <div class="search-box">
                                <div class="input-group">
                                    <input type="search" class="form-control" placeholder="دنبال چی میگردی ؟"
                                           aria-label="Recipient's username" aria-describedby="button-addon2">
                                    <button class="btn bg-theme" type="button" id="button-addon2">
                                        <i data-feather="search"></i>
                                    </button>
                                </div>
                            </div>
                        </div>

                        <div class="rightside-box">
                            <div class="search-full">
                                <div class="input-group">
                                    <span class="input-group-text">
                                        <i data-feather="search" class="font-light"></i>
                                    </span>
                                    <input type="text" class="form-control search-type" placeholder="Search here..">
                                    <span class="input-group-text close-search">
                                        <i data-feather="x" class="font-light"></i>
                                    </span>
                                </div>
                            </div>
                            <ul class="right-side-menu">
                                <li class="right-side">
                                    <div class="delivery-login-box">
                                        <div class="delivery-icon">
                                            <div class="search-box">
                                                <i data-feather="search"></i>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li class="right-side">
                                    <a href="contact-us.html" class="delivery-login-box">
                                        <div class="delivery-icon">
                                            <i data-feather="phone-call"></i>
                                        </div>
                                        <div class="delivery-detail">
                                            <h6>پشتیبانی 24 ساعته</h6>
                                            <h5>012345678</h5>
                                        </div>
                                    </a>
                                </li>
                                <li class="right-side">
                                    <a href="wishlist.html" class="btn p-0 position-relative header-wishlist">
                                        <i data-feather="heart"></i>
                                    </a>
                                </li>
                                <li class="right-side">
                                    <div class="onhover-dropdown header-badge">
                                        <button type="button" class="btn p-0 position-relative header-wishlist">
                                            <i data-feather="shopping-cart"></i>
                                            <span class="position-absolute top-0 start-100 translate-middle badge">
                                                2
                                                <span class="visually-hidden">پیام جدید</span>
                                            </span>
                                        </button>

                                        <div class="onhover-div">
                                            <ul class="cart-list">
                                                <li class="product-box-contain">
                                                    <div class="drop-cart">
                                                        <a href="product-left-thumbnail.html" class="drop-image">
                                                            <img src="/siteAssets/images/vegetable/product/1.png"
                                                                 class="blur-up lazyload" alt="">
                                                        </a>

                                                        <div class="drop-contain">
                                                            <a href="product-left-thumbnail.html">
                                                                <h5>کوکی های ترد فانتزی شکلات چیپ</h5>
                                                            </a>
                                                            <h6><span>1 x</span> 80.250 تومان</h6>
                                                            <button class="close-button close_button">
                                                                <i class="fa-solid fa-xmark"></i>
                                                            </button>
                                                        </div>
                                                    </div>
                                                </li>

                                                <li class="product-box-contain">
                                                    <div class="drop-cart">
                                                        <a href="product-left-thumbnail.html" class="drop-image">
                                                            <img src="/siteAssets/images/vegetable/product/2.png"
                                                                 class="blur-up lazyload" alt="">
                                                        </a>

                                                        <div class="drop-contain">
                                                            <a href="product-left-thumbnail.html">
                                                                <h5>
                                                                    بیسکویت کره بادام زمینی پرمیوم کره 600 گرم
                                                                </h5>
                                                            </a>
                                                            <h6><span>1 x</span> 25.650 تومان</h6>
                                                            <button class="close-button close_button">
                                                                <i class="fa-solid fa-xmark"></i>
                                                            </button>
                                                        </div>
                                                    </div>
                                                </li>
                                            </ul>

                                            <div class="price-box">
                                                <h5>جمع کل :</h5>
                                                <h4 class="theme-color fw-bold">106.000 تومان</h4>
                                            </div>

                                            <div class="button-group">
                                                <a href="cart.html" class="btn btn-sm cart-button">سبد خرید</a>
                                                <a href="checkout.html" class="btn btn-sm cart-button theme-bg-color
                                                    text-white">پرداخت</a>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li class="right-side onhover-dropdown">
                                    <div class="delivery-login-box">
                                        <div class="delivery-icon">
                                            <i data-feather="user"></i>
                                        </div>
                                        <div class="delivery-detail">
                                            <h6>درود,</h6>
                                            <h5>حساب کاربری</h5>
                                        </div>
                                    </div>

                                    <div class="onhover-div onhover-div-login">
                                        <ul class="user-box-name">
                                            <li class="product-box-contain">
                                                <i></i>
                                                <a href="login.html">ورود</a>
                                            </li>

                                            <li class="product-box-contain">
                                                <a href="sign-up.html">عضویت</a>
                                            </li>

                                            <li class="product-box-contain">
                                                <a href="forgot.html">فراموشی رمزعبور</a>
                                            </li>
                                        </ul>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>
<!-- Header End -->
<!-- mobile fix menu start -->
<div class="mobile-menu d-md-none d-block mobile-cart">
    <ul>
        <li class="active">
            <a href="index.html">
                <i class="iconly-Home icli"></i>
                <span>خانه</span>
            </a>
        </li>

        <li class="mobile-category">
            <a href="javascript:void(0)">
                <i class="iconly-Category icli js-link"></i>
                <span>دسته بندی</span>
            </a>
        </li>

        <li>
            <a href="search.html" class="search-box">
                <i class="iconly-Search icli"></i>
                <span>جستجو</span>
            </a>
        </li>

        <li>
            <a href="wishlist.html" class="notifi-wishlist">
                <i class="iconly-Heart icli"></i>
                <span>علاقه مندی</span>
            </a>
        </li>

        <li>
            <a href="cart.html">
                <i class="iconly-Bag-2 icli fly-cate"></i>
                <span>سبد خرید</span>
            </a>
        </li>
    </ul>
</div>
<!-- mobile fix menu end -->

OnlineShop.Web/Views/Shared/Partials/_Link.cshtml
<link rel="icon" href="/siteAssets/images/favicon/6.png" type="image/x-icon">
<!-- Google font -->
<link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Russo+One&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Pacifico&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Kaushan+Script&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Exo+2:wght@400;500;600;700;800;900&display=swap"
      rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Public+Sans:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
      rel="stylesheet">

<!-- bootstrap css -->
<link id="rtl-link" rel="stylesheet" type="text/css" href="/siteAssets/css/vendors/bootstrap.css">

<!-- wow css -->
<link rel="stylesheet" href="/siteAssets/css/animate.min.css" />

<!-- font-awesome css -->
<link rel="stylesheet" type="text/css" href="/siteAssets/css/vendors/font-awesome.css">

<!-- feather icon css -->
<link rel="stylesheet" type="text/css" href="/siteAssets/css/vendors/feather-icon.css">

<!-- slick css -->
<link rel="stylesheet" type="text/css" href="/siteAssets/css/vendors/slick/slick.css">
<link rel="stylesheet" type="text/css" href="/siteAssets/css/vendors/slick/slick-theme.css">

<!-- Iconly css -->
<link rel="stylesheet" type="text/css" href="/siteAssets/css/bulk-style.css">
<link rel="stylesheet" type="text/css" href="/siteAssets/css/vendors/animate.css">

<!-- Template css -->
<link id="color-link" rel="stylesheet" type="text/css" href="/siteAssets/css/style.css">
<link rel="stylesheet" href="/siteAssets/css/custom.css">
<link rel="stylesheet" href="/siteAssets/css/font.css">

OnlineShop.Web/Views/Shared/Partials/_MetaTag.cshtml
<title>فروشگاه آنلاین ابوالفضل و ممدوسین</title>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="Fastkart">
<meta name="keywords" content="Fastkart">
<meta name="author" content="Fastkart">

OnlineShop.Web/Views/Shared/Partials/_Script.cshtml
<script src="/siteAssets/js/jquery-3.6.0.min.js"></script>

<!-- jquery ui-->
<script src="/siteAssets/js/jquery-ui.min.js"></script>

<!-- Bootstrap js-->
<script src="/siteAssets/js/bootstrap/bootstrap.bundle.min.js"></script>
<script src="/siteAssets/js/bootstrap/bootstrap-notify.min.js"></script>
<script src="/siteAssets/js/bootstrap/popper.min.js"></script>

<!-- feather icon js-->
<script src="/siteAssets/js/feather/feather.min.js"></script>
<script src="/siteAssets/js/feather/feather-icon.js"></script>

<!-- Lazyload Js -->
<script src="/siteAssets/js/lazysizes.min.js"></script>

<!-- Slick js-->
<script src="/siteAssets/js/slick/slick.js"></script>
<script src="/siteAssets/js/slick/slick-animation.min.js"></script>
<script src="/siteAssets/js/slick/custom_slick.js"></script>

<!-- Auto Height Js -->
<script src="/siteAssets/js/auto-height.js"></script>

<!-- Fly Cart Js -->
<script src="/siteAssets/js/fly-cart.js"></script>

<!-- Quantity js -->
<script src="/siteAssets/js/quantity-2.js"></script>

<!-- WOW js -->
<script src="/siteAssets/js/wow.min.js"></script>
<script src="/siteAssets/js/custom-wow.js"></script>

<!-- script js -->
<script src="/siteAssets/js/script.js"></script>

<!-- thme setting js -->
<script src="/siteAssets/js/theme-setting.js"></script>

<!-- latest jquery-->

OnlineShop.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="fa" dir="rtl">

<head>
    <partial name="Partials/_MetaTag" />
    <partial name="Partials/_Link" />
</head>

<body class="theme-color-4 bg-gradient-color">

    <partial name="Partials/_Header" />
    <!-- Product Section Start -->
    @RenderBody()
    <!-- Product Section End -->
    <partial name="Partials/_Footer" />
    <partial name="Partials/_Modal" />
    <!-- Bg overlay Start -->
    <div class="bg-overlay"></div>
    <!-- Bg overlay End -->
    <partial name="Partials/_Script" />

</body>

</html>